### ISSUE TITLE
Building dev branch

### ISSUE THREAD

**Issue by l4l** [fabsx00/joern#100]
Is it intended to build the dev branch or it's not ready yet?

I've tried couple of times with different versions of openjdk(7 & 8). I delete unnecessary info from logs, feel free to ask the full ones

For `gradle jar`/`gradle classes` with openjdk-8:
```
:projects:joern-pluginlib:compileJava .../projects/joern-pluginlib/src/main/java/joern/pluginlib/plugintypes/JoernProjectPlugin.java:4: error: cannot find symbol
import octopus.lib.plugintypes.OctopusProjectPlugin;
                              ^
  symbol:   class OctopusProjectPlugin
  location: package octopus.lib.plugintypes
.../projects/joern-pluginlib/src/main/java/joern/pluginlib/plugintypes/JoernProjectPlugin.java:6: error: cannot find symbol
public class JoernProjectPlugin extends OctopusProjectPlugin {
                                        ^
  symbol: class OctopusProjectPlugin
.../projects/joern-pluginlib/src/main/java/joern/pluginlib/plugintypes/JoernProjectPlugin.java:10: error: cannot find symbol
                setProjectConnector(new JoernProjectConnector());
                ^
  symbol:   method setProjectConnector(JoernProjectConnector)
  location: class JoernProjectPlugin
3 errors

BUILD FAILED
```

With `gradle build` & openjdk-8 build fails on tests(due to version maybe?):
```
:projects:joern-fuzzyc:test

tests.ddg.testDDGCreator > simplestTest FAILED
    java.util.NoSuchElementException at testDDGCreator.java:33

tests.ddg.testDDGCreator > testConverter FAILED
    java.util.NoSuchElementException at testDDGCreator.java:55

tests.argumentTainter.TestArgumentTainter > testDefUseCFGPatcher FAILED
    java.util.NoSuchElementException at TestArgumentTainter.java:65

135 tests completed, 3 failed
:projects:joern-fuzzyc:test FAILED
```
And finally `gradle build`/`gradle jar`/`gradle classes` & openjdk-7 fails on lambdas at [CG.java](https://github.com/fabsx00/joern/blob/dev/projects/jpanlib/src/main/java/cg/CG.java) due to it's unsupported at 7th version

**Comment by fabsx00** [comment]
Pull, and retry, please.

**Comment by l4l** [comment]
What's the preferable build command & java version? It seems still not working

**Comment by fabsx00** [comment]
The preferable build-command is `./build.sh`, and you need openjdk-8. Please try a `gradle clean` first, if you've encountered failed builds. If all else fails, please try to clone the repository again, and then execute `./build.sh`.

**Comment by fabsx00** [comment]
Just confirmed that this works on a freshly cloned dev-branch.

**Comment by l4l** [comment]
Didn't find any issues
Looks like everything is fine now. Thanks! :)
