### ISSUE TITLE
Question about Python C API analysis

### ISSUE THREAD

**Issue by esc** [fabsx00/joern#42]
Question: would it be possible to analyze Python C extensions with joern?

**Comment by fabsx00** [comment]
if they are written in C, I see no reason why not.

**Comment by esc** [comment]
Yes, they are written in C, but use many Python specific macros and conventions. For example there is this project:

http://gcc-python-plugin.readthedocs.org/en/latest/cpychecker.html

which does static analysis of such C extensions. I am wondering if joern could be a substitute for it or if it would be complimentary?

**Comment by fabsx00** [comment]
I'd say it's worth a try since C extensions for python can definitely be an interesting target. My guess is that it works pretty well and only skips some of the macros it doesn't understand. Let me know if you run into trouble and I'll see what I can do to help out.

**Comment by esc** [comment]
OK. I'll close this issues for now and open a new one if I do find the time to try it and run into issues. Thanks!
