### ISSUE TITLE
Does not appear to work with Neo4j-2.1.6

### ISSUE THREAD

**Issue by pmarkowsky** [fabsx00/joern#43]
I'm attempting to containerize joern, as I'd like to make it super easy to install and use out of the box.

When attempting to follow the tutorial in my container, built with the Dockerfile below I keep running into an error indicating that the database created by joren is corrupted. This error appears in neo4j's console.log when attempting to start the neo4j-server with the org.neo4j.server.database.location set to my own .jorenIndex directory.

<pre>
2015-01-14 21:58:52.962+0000 INFO  [API] Setting startup timeout to: 120000ms based on -1
Detected incorrectly shut down database, performing recovery..
</pre>

Steps to reproduce

Build the joern container
1.) run docker build --tag=joern-0.3.1 . from a directory with the attached Dockerfile

This uses neo4j's PPA to install the server from packages the current version is 2.1.6 (as it is hard to find exact packages / downloads for 2.1.5)

2.) run the container

docker run -it --privileged --name joern joern-0.3.1 /bin/bash

3.) inside the contianer from the root prompt up your file via ulimit -n 65535

This is to work around an dockers settings and also why we need to use --privileged.

4.) cd to the $JOERN dirctory (/opt/joern-0.3.1) and 
4a.) create subdir named tutorial
4b.) download vlc-2.1.4 to that directory 
4c.) cd to /opt/joren-0.3.1 and run ./joren tutorial/vlc-2.1.4 to create the .jorenIndex in /opt/joern-0.3.1

5.) Edit /etc/neo4j/neo4j-server.properties to point to /opt/joern-0.3.1/.jorenIndex/

namely make these changes
<pre>
#location of the database directory
#org.neo4j.server.database.location=data/graph.db
org.neo4j.server.database.location=/opt/joern-0.3.1/.joernIndex/
</pre>

6.) Attempt to start neo4j via services command service neo4j-service start

This will fail like the following:
<pre>
root@6ae06dfe9067:/opt/joern-0.3.1# service neo4j-service start
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow
Starting Neo4j Server...WARNING: not changing user
process [692]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
</pre>

7.) check /var/log/neo4j/console.log to see the aforementioned error message.

Since I can't attach the Dockerfile in a ticket below are its contents.

<pre>
FROM ubuntu:latest
MAINTAINER Pete Markowsky <peterm@vodun.org>
RUN apt-get update && apt-get install -y wget unzip git && apt-get clean
#Add the official neo4j PPA
RUN wget -O - http://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
RUN echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list.d/neo4j.list 
# install packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y openjdk-7-jdk python-dev python-setuptools python-pip graphviz libgraphviz-dev neo4j ant python-pygraphviz python-pip && apt-get clean
# install joern 
RUN cd /opt/ && wget https://github.com/fabsx00/joern/archive/0.3.1.tar.gz && tar xfzv 0.3.1.tar.gz
RUN cd /opt/joern-0.3.1 && wget http://mlsec.org/joern/lib/lib.tar.gz && tar xfzv lib.tar.gz
RUN cd /opt/joern-0.3.1 && ant
# Install gremlin plugin
RUN cd /tmp && wget -O neo4j-gremlin.zip http://mlsec.org/joern/lib/neo4j-gremlin-plugin-2.1-SNAPSHOT-server-plugin.zip && unzip neo4j-gremlin.zip -d /usr/share/neo4j/plugins/gremlin-plugin
#install joern tools
RUN cd /tmp/ && git clone https://github.com/fabsx00/joern-tools && cd joern-tools && python2 setup.py install
</pre>

**Comment by fabsx00** [comment]
Hi,
first of all: thanks for your effort :) Let me know how it turns out.

Can you be so kind and try out the 2.1.5 version so that we can be sure that it's a problem with 2.1.6?

Here is the tarball: http://neo4j.com/download-thanks/?edition=community&release=2.1.5&flavour=unix

If it really is a problem with 2.1.6, I will update joern to user neo4j 2.1.6 and that will hopefully fix the problem.

Thanks,
fabs

**Comment by fabsx00** [comment]
One more thing that comes to mind: are you sure the permissions on .joernIndex are correctly set so that the neo4j-server can access the directory?

**Comment by pmarkowsky** [comment]
Ugh, permissions were the issue. Sorry about that.

I'll need to update the Dockerfile to set the umask or something.

<pre>
root@ea06fb7fc19d:/opt/joern-0.3.1#  service neo4j-service start
...output snipped...
Process [313]... waiting for server to be ready.... OK.
http://localhost:7474/ is ready.
root@ea06fb7fc19d:/opt/joern-0.3.1# echo 'g.v(0).out()' | joern-lookup -g

(n2351381 {filepath:"/opt/joern-0.3.1/tutorial/vlc-2.1.4/test",type:"Directory"})
(n2010797 {filepath:"/opt/joern-0.3.1/tutorial/vlc-2.1.4/src",type:"Directory"})
...snipped...
</pre>

But that said the Dockerfile works to produce a container with an installed version of joern e.g. 
you just need to do the following.

<pre>
docker build --tag=joren-0.3.1 .
</pre>

I'll try to clean up what I have and submit a PR.
