### ISSUE TITLE
The Child Num Bug of IdentifierDecl

### ISSUE THREAD

**Issue by yangke** [fabsx00/joern#54]
Hi,fabs or other kind person who can help
  When I use joern to parse linux-3.9.1/drivers/usb/class/cdc-wdm.c.I found it gives wrong children AST node numbers for the declaration statement like
```
int status = urb->status;
```
I run this command:
```
echo "queryNodeIndex('type:IdentifierDecl').filter{it.code.contains(\"status\")}.out()" |joern-lookup -g
```
and got the following output 
```
(n579 {childNum:"0",code:"int",functionId:301,type:"IdentifierDeclType"})
(n578 {childNum:"0",code:"status",functionId:301,type:"Identifier"})
(n573 {childNum:"2",code:"status = urb -> status",functionId:301,operator:"=",type:"AssignmentExpr"})
(n1080 {childNum:"0",code:"int",functionId:618,type:"IdentifierDeclType"})
(n1079 {childNum:"0",code:"status",functionId:618,type:"Identifier"})
(n1074 {childNum:"2",code:"status = urb -> status",functionId:618,operator:"=",type:"AssignmentExpr"})
```
It seems the  "childNum"  of the  "Identifier" type node  is wrongly assigned with "0".
But the "childNum" property should be "1".

**Comment by fabsx00** [comment]
Yes, that seems like a bug. Unfortunately, I'm pretty busy with other things right now so I wont come around to fix it very soon. Is this crucial to what you're doing? If so, I'll try to find some time.
Thanks for reporting this.

**Comment by yangke** [comment]
Oh,there is no rush. I'll look into this bug case too.Thank you!

**Comment by yangke** [comment]
hi,fabs. 
I find this problem is caused by line:548 in FunctionContentBuilder.java.
```
assign.addChild(identifierDecl.getName());
```
This statement add the child(class type:Identifier) of identifierDecl(class type:IdentifierDecl) to assgin(class type:AssignmentExpr). The childnum of this child is modified by the addChild method, thus it is wrong for the original parent identifierDecl.

Fix this problem by clone this child. See pull request #62 .

**Comment by fabsx00** [comment]
Hi,
I just reviewed this code and your pull request, and I'm not really happy with the entire handling of IdentifierDecls that contain assignments. I'm going to rewrite this part completely to simplify it.
