### ISSUE TITLE
[phpbranch] getCondition() on PHPIfStatements returns null

### ISSUE THREAD

**Issue by fabsx00** [fabsx00/joern#95]
Calling getCondition() on PHPIfStatements currently returns null. I modified testIfStatementCreation to trigger this.

**Comment by einheitlix** [comment]
This is correct. A `PHPIfStatement` has no condition. It only has a list of `PHPIfElement` nodes which each have a condition and a statement. Please see PR #79 where I describe the AST structure of if statements in more detail, as well as the comments above the tests `testIfStatementCreation()` and `testIfElementCreation()` in `TestPHPCSVASTBuilder`.

**Comment by einheitlix** [comment]
Note: I should probably modify `PHPIfStatement` to throw a `RuntimeException` if one tries to call `getCondition()` on it. It only has this method because it is inherited from `BlockStarter`. However, I don't want to mess with the code now while you are working on this. :)

**Comment by fabsx00** [comment]
I've simply written custom code to handle this for now. Closing.
